version: 2

jobs:
  ruby25: &base
    docker:
       - image: circleci/ruby:2.5

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gemfile" }}
          - v1-dependencies-{{ .Environment.CIRCLE_JOB }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gemfile" }}

      - run:
          name: run tests
          command: |
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \

      - run:
          name: rubocop
          command: bundle exec rubocop -D

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  ruby26:
    <<: *base
    docker:
      - image: circleci/ruby:2.6

workflows:
  version: 2
  build:
    jobs:
      - ruby25
      - ruby26
